@startuml sys-arch

skinparam nodesep 60
skinparam ranksep 10
'skinparam linetype polyline

actor "Utente" as user

node "Computer" as pc{

    rectangle "IDE" as ide
    rectangle "GDB" as gdb

    ide <--left--> gdb #FF0000 : stdio 

}

node "ATMega16U2" as srv {

    rectangle "GDB Server" as gdbsrv
    rectangle "DebugWire Impl" as dw

    gdbsrv --right--> dw: Usa
}

node "AVR Target" as avr

user --down--> ide: Utilizza

pc <--down--> srv #0000FF: USB CDC
gdb <-down-> gdbsrv: GDB Server Protocol
srv <--> avr #0000FF: DebugWire
dw --> avr: Debug
gdbsrv <-down-> avr: RTT
@enduml